service: madziki

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs6.10
  profile: serverless-user
  stage: dev
  #  deploymentBucket: madziki-serverless
  memorySize: 256
   # Allow for cf "AWS::" variables, see https://serverless.com/framework/docs/providers/aws/guide/variables#using-custom-variable-syntax
#  variableSyntax: "\\${(?!AWS::)([ :a-zA-Z0-9._,\\-\\/\\(\\)]+?)}"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:*:553670172214:table/madziki-*
  environment:
    MOVEMENTS_TABLE: { "Ref": "MovementsTable" } #DynamoDbExpenses is a logicalID also used when provisioning below
    USERS_TABLE: { "Ref": "UsersTable" }

#plugins:
#  - serverless-localstack

functions:
  postMovement:
    handler: index.postMovement
    events:
      - http:
          path: movements
          method: post
  putMovement:
    handler: index.putMovement
    events:
      - http:
          path: movements
          method: put
  getMovement:
    handler: index.getMovement
    events:
      - http:
          path: movements
          method: get
  listMovements:
    handler: index.listMovements
    events:
      - http:
          path: movements
          method: get
  deleteMovement:
    handler: index.deleteMovement
    events:
      - http:
          path: movements
          method: delete

package:
  exclude:
    - ./**
  include:
    - index.js

resources:
  Resources:
    MovementsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
        - AttributeName: Owner
          AttributeType: S
        KeySchema:
        - AttributeName: Owner
          KeyType: HASH
        - AttributeName: Name
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
#        TableName: 'madziki-movements'
        TableName:
          Fn::Join:
            - '-'
            - - Ref: AWS::StackName
              - "movements"

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
        - AttributeName: Username
          AttributeType: S
        - AttributeName: Active
          AttributeType: B
        KeySchema:
        - AttributeName: Username
          KeyType: HASH
        - AttributeName: Active
          KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: '5'
          WriteCapacityUnits: '5'
#        TableName: 'madziki-users'
        TableName:
          Fn::Join:
            - '-'
            - - Ref: AWS::StackName
              - 'users'

#custom:
#  localstack:
#    stages:
#      - dev
#    host: http://localhost:8080
#    endpoints:
#      S3: http://localhost:4572
#      DynamoDB: http://localhost:4569
#      CloudFormation: http://localhost:4581
#      Elasticsearch: http://localhost:4571
#      ES: http://localhost:4578
#      SNS: http://localhost:4575
#      SQS: http://localhost:4576
#      Lambda: http://localhost:4574
#      Kinesis: http://localhost:4568
